[SK-14] add: custom filters (date, user, tags), pagination, tests
skygate/sky-lectures pull request #11
Opened 2021-09-02 13:04 UTC by danielkosytorz

- Create custom filter class (date, user, tags)
- Create custom pagination class
- Create tests

2021-09-02 13:45 UTC, blacha370 commented on backend/presentation/views.py
> +    filter_backends = (filters.DjangoFilterBackend,)
Stay with one convention for iterative properties in views. 
```suggestion
    filter_backends = [filters.DjangoFilterBackend]
```

2021-09-02 13:45 UTC, blacha370 commented on backend/presentation/paginations.py
> +    page_size = 10
There is no reason to create multiple Pagination classes with same attributes.

2021-09-03 07:25 UTC, fiedosiukr commented on backend/presentation/views.py
> +    filter_backends = (filters.DjangoFilterBackend,)
You can also specify the default `DEFAULT_FILTER_BACKENDS` in the settings file.

2021-09-03 07:37 UTC, fiedosiukr requested changes

2021-09-03 07:37 UTC, fiedosiukr commented on backend/presentation/paginations.py
> +    page_size = 10
You can also specify `DEFAULT_PAGINATION_CLASS` in the settings files. There is no need to create exactly the same classes with different names.

2021-09-03 07:37 UTC, fiedosiukr commented on backend/presentation/tests.py
> +        )
Let's add [factory_boy](https://factoryboy.readthedocs.io/en/stable/) to make things cleaner.

2021-09-06 06:24 UTC, fiedosiukr requested changes

2021-09-06 06:24 UTC, fiedosiukr commented on backend/presentation/paginations.py
> +class PresentationAndTagSetPagination(PageNumberPagination):
I would suggest to rename the class. What if you would like to add `pagintion_class` to another `ViewSet?` Will you rename it to `PresentationAndTagAndAnotherModelSetPagination`?
```suggestion
class StandardResultsSetPagination(PageNumberPagination):
```

2021-09-06 06:24 UTC, fiedosiukr commented on backend/presentation/tests.py
> +            scheduled_on=datetime(2021, 10, 1, 12, 0, tzinfo=pytz.UTC),
Good job! The code looks definitely much cleaner now.

2021-09-06 06:24 UTC, fiedosiukr commented on backend/presentation/filters.py
> +        fields = ["scheduled_on", "user", "tags"]
It would probably be better to filter by the user's username instead of the user's id.
Same thing applies for tags.

2021-09-07 08:24 UTC, merged