[SK-1] change custom user model to AbstractUser, add Profile model, use signal to create profile instance
skygate/sky-lectures pull request #7
Opened 2021-08-27 08:01 UTC by kszuster

2021-08-27 08:46 UTC, jakub-figat commented on backend/sky_lectures/settings/base.py
> +MEDIA_ROOT = BASE_DIR + '/static/media/'
```suggestion
MEDIA_ROOT = '/media/'
```

2021-08-27 08:46 UTC, jakub-figat commented on backend/sky_lectures/urls.py
> +urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```suggestion
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```

2021-08-27 08:46 UTC, jakub-figat commented on backend/users/apps.py
> +        import users.signals
👍

2021-08-27 08:46 UTC, jakub-figat commented on backend/users/models.py
> +        primary_key=True, default=uuid.uuid4, editable=False, unique=True, name="id"
```suggestion
        primary_key=True, default=uuid.uuid4, editable=False
```

2021-08-27 08:46 UTC, jakub-figat commented on backend/users/models.py
> +    os.remove(os.path.join(settings.MEDIA_ROOT, "images/", filename))
The function name is a bit misleading here, since function does not only get the file path, but also remove file from filesystem. Moreover, if the file didn't exist before, `OSError` will be raised. I recommend moving this functionality to `pre_save` signal.

2021-08-27 08:46 UTC, jakub-figat commented on backend/users/models.py
> +    file = models.ImageField(upload_to=get_file_path, blank=True)
If I remember correctly, we've discussed that image should be separate model with `OneToOne` relationship with `User`.

2021-08-27 08:46 UTC, jakub-figat commented on backend/users/models.py
> +        return self.user.username
This could be more descriptive, maybe something like `f"Profile of user {self.user.username}"`

2021-08-27 09:16 UTC, wojciechczarnecki commented on backend/users/models.py
> +    os.remove(os.path.join(settings.MEDIA_ROOT, "images/", filename))
Additionally, I would encourage you to use `pathlib.Path` instead of `os.path.join`.

2021-08-27 09:19 UTC, wojciechczarnecki commented on backend/sky_lectures/settings/dev.py
>  from sky_lectures.settings.base import *
[Wildcard imports should be avoided, in most cases, in most caseeeeeees](https://www.youtube.com/watch?v=hgI0p1zf31k&ab_channel=PythonDiscord)

2021-08-27 13:54 UTC, jakub-figat commented on backend/users/signals.py
> +        os.remove(os.path.join(settings.MEDIA_ROOT, file_path))
No need to use `get_file_path` here, because you can access photo path using `instance.file.path`

```suggestion
def remove_old_image(sender, instance, **kwargs):
    file_path = instance.file.path
    if os.path.exists(file_path):
        os.remove(file_path)
```

2021-08-27 13:54 UTC, jakub-figat commented on backend/users/signals.py
> +        os.remove(os.path.join(settings.MEDIA_ROOT, file_path))
There's one major problem with current implementation. Even when user updates field on profile model unrelated to image, the image will be deleted anyway. One way to avoid this, is to check if `"file"` is in `update_fields` kwarg passed when signal is invoked. Downside of that approach is that you always have to call `profile.save(update_fields=[...])`.
Second way is creating separate model for image and connecting `pre_save` to it.

2021-08-28 08:00 UTC, fiedosiukr requested changes

2021-08-28 08:00 UTC, fiedosiukr commented on backend/sky_lectures/settings/base.py
> +MEDIA_ROOT = BASE_DIR + '/static/media/'
Please use double quotes.

2021-08-28 08:00 UTC, fiedosiukr commented on backend/sky_lectures/settings/dev.py
>  from sky_lectures.settings.base import *
I guess it's ok to use it in this case.

2021-08-28 08:00 UTC, fiedosiukr commented on backend/users/admin.py
> +from users.models import Profile, User
Please add a blank line.

2021-08-28 08:00 UTC, fiedosiukr commented on backend/users/models.py
> +    return os.path.join("images/", filename)
Is it really necessary to create a variable when you use it only once?
```suggestion
    return os.path.join("images/", f"avatar_image_{instance.user.id}.jpeg")
```

2021-08-28 08:00 UTC, fiedosiukr commented on backend/users/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
`editable=False` is redundant. You can read more [here](https://docs.djangoproject.com/en/3.2/ref/models/fields/#primary-key).

2021-08-28 08:00 UTC, fiedosiukr commented on backend/users/models.py
> +    )
r
```suggestion
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
```
Once again, there is no need to add `editable` when you use `primary_key`. When using OneToOneField `related_name` by default is equal to the class name.

2021-08-30 06:40 UTC, jakub-figat commented on backend/sky_lectures/settings/base.py
> +MEDIA_ROOT = BASE_DIR + '/static/media/'
Even better would be code formatter (Black, isort).

2021-08-31 07:47 UTC, fiedosiukr requested changes

2021-08-31 07:47 UTC, fiedosiukr commented on backend/sky_lectures/settings/base.py
> +
Once again, change single quotes to double ones.

2021-08-31 07:47 UTC, fiedosiukr commented on .gitignore
> +**/migrations/*
Why is it added there?

2021-08-31 11:15 UTC, fiedosiukr approved these changes

2021-08-31 11:29 UTC, merged