[SK-19] create user endpoints, create tests
skygate/sky-lectures pull request #8
Opened 2021-08-27 08:45 UTC by danielkosytorz

- Create user endpoints
- Create tests for user endpoints

2021-08-27 08:54 UTC, wojciechczarnecki commented on backend/users/permissions.py
> +            return True
```suggestion
    def has_object_permission(self, request, view, obj):
        return request.method in SAFE_METHODS:
```

2021-08-27 10:28 UTC, danielkosytorz commented on backend/users/permissions.py
> +            return True
It can't be like that because in this way the rest of the function don't check if the user is owner or admin, it just return False if the method is not in SAFE_METHODS.

2021-08-27 13:53 UTC, fiedosiukr requested changes

2021-08-27 13:53 UTC, fiedosiukr commented on backend/users/serializers.py
> +        ]
We should keep things consistent, change single quotes to double ones.

2021-08-27 13:53 UTC, fiedosiukr commented on backend/users/tests.py
> +        cls.token_url = reverse("token_obtain_pair")
I guess it is not used anywhere.

2021-08-27 13:53 UTC, fiedosiukr commented on backend/users/tests.py
> +        # self.client.credentials(HTTP_AUTHORIZATION='Bearer ' + token)
Let's remove those comments.

2021-08-27 13:53 UTC, fiedosiukr commented on backend/users/views.py
> +    queryset = User.objects.all()
There may be some inactive users in the future, considering filtering only active users.
```suggestion
    queryset = User.objects.filter(is_active=True)
```

2021-08-27 13:59 UTC, jakub-figat commented on backend/users/permissions.py
> +            return True
To me, it looks like syntactial change only, not affecting behavior, have you tested it?

2021-08-27 13:59 UTC, jakub-figat commented on backend/users/tests.py
> +class UsersEndpointsTestCase(APITestCase):
```suggestion
class TestUserViewSet(APITestCase):
```

2021-08-28 07:38 UTC, danielkosytorz commented on backend/users/permissions.py
> +            return True
I have tested it and it affects behavior.

2021-08-28 07:47 UTC, fiedosiukr approved these changes

2021-08-28 07:47 UTC, fiedosiukr commented on backend/users/permissions.py
> +            return True
It has to be like that.

2021-08-30 11:31 UTC, merged